---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: msugakov
    pac.test.appstudio.openshift.io/sha-title: Add 4.7.6 version (#174)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/e1eb04597589f6dd41cecc75cfe81570e9ad655b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-12-llcnd
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-12
    appstudio.openshift.io/component: operator-index-ocp-v4-12
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: e1eb04597589f6dd41cecc75cfe81570e9ad655b
  name: acs-operator-index-ocp-v4-12-2025-08-20-e1eb045-prod
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-12
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:631bbe44d77ce83f54fc35b5cb00bf830fbb8c75395e140463739e03d9a78c80
      name: operator-index-ocp-v4-12
      source:
        git:
          revision: e1eb04597589f6dd41cecc75cfe81570e9ad655b
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-12-20250820-e1eb045-prd
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-12
  snapshot: acs-operator-index-ocp-v4-12-2025-08-20-e1eb045-prod
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: msugakov
    pac.test.appstudio.openshift.io/sha-title: Add 4.7.6 version (#174)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/e1eb04597589f6dd41cecc75cfe81570e9ad655b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-13-4djqr
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-13
    appstudio.openshift.io/component: operator-index-ocp-v4-13
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: e1eb04597589f6dd41cecc75cfe81570e9ad655b
  name: acs-operator-index-ocp-v4-13-2025-08-20-e1eb045-prod
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-13
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:e51cdb99087c0815b4e617c00b2d63c21f3cab06c8282ccc742bc41762848546
      name: operator-index-ocp-v4-13
      source:
        git:
          revision: e1eb04597589f6dd41cecc75cfe81570e9ad655b
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-13-20250820-e1eb045-prd
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-13
  snapshot: acs-operator-index-ocp-v4-13-2025-08-20-e1eb045-prod
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: msugakov
    pac.test.appstudio.openshift.io/sha-title: Add 4.7.6 version (#174)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/e1eb04597589f6dd41cecc75cfe81570e9ad655b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-14-bw5hg
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-14
    appstudio.openshift.io/component: operator-index-ocp-v4-14
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: e1eb04597589f6dd41cecc75cfe81570e9ad655b
  name: acs-operator-index-ocp-v4-14-2025-08-20-e1eb045-prod
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-14
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:1a8082a5177cf2c926e59756dd4bf61948bd8bd53164eab7155e2bca0dfcdb26
      name: operator-index-ocp-v4-14
      source:
        git:
          revision: e1eb04597589f6dd41cecc75cfe81570e9ad655b
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-14-20250820-e1eb045-prd
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-14
  snapshot: acs-operator-index-ocp-v4-14-2025-08-20-e1eb045-prod
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: msugakov
    pac.test.appstudio.openshift.io/sha-title: Add 4.7.6 version (#174)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/e1eb04597589f6dd41cecc75cfe81570e9ad655b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-15-rrk5r
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-15
    appstudio.openshift.io/component: operator-index-ocp-v4-15
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: e1eb04597589f6dd41cecc75cfe81570e9ad655b
  name: acs-operator-index-ocp-v4-15-2025-08-20-e1eb045-prod
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-15
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:98f84cde0f2600dfd1bcdf77216ea1ad8e7bcd82002128acbe863561a856dc49
      name: operator-index-ocp-v4-15
      source:
        git:
          revision: e1eb04597589f6dd41cecc75cfe81570e9ad655b
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-15-20250820-e1eb045-prd
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-15
  snapshot: acs-operator-index-ocp-v4-15-2025-08-20-e1eb045-prod
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: msugakov
    pac.test.appstudio.openshift.io/sha-title: Add 4.7.6 version (#174)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/e1eb04597589f6dd41cecc75cfe81570e9ad655b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-16-bkvmn
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-16
    appstudio.openshift.io/component: operator-index-ocp-v4-16
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: e1eb04597589f6dd41cecc75cfe81570e9ad655b
  name: acs-operator-index-ocp-v4-16-2025-08-20-e1eb045-prod
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-16
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:6f9983b7c130b94598bd2049cccbf1ec87a045b17d0a7f19669475ac8b798811
      name: operator-index-ocp-v4-16
      source:
        git:
          revision: e1eb04597589f6dd41cecc75cfe81570e9ad655b
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-16-20250820-e1eb045-prd
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-16
  snapshot: acs-operator-index-ocp-v4-16-2025-08-20-e1eb045-prod
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: msugakov
    pac.test.appstudio.openshift.io/sha-title: Add 4.7.6 version (#174)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/e1eb04597589f6dd41cecc75cfe81570e9ad655b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-17-fl9dq
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-17
    appstudio.openshift.io/component: operator-index-ocp-v4-17
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: e1eb04597589f6dd41cecc75cfe81570e9ad655b
  name: acs-operator-index-ocp-v4-17-2025-08-20-e1eb045-prod
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-17
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:97f83b614a2ae83ad774ba38ed92ff503f9e3764e0f0c2f8e722ff20e9911aef
      name: operator-index-ocp-v4-17
      source:
        git:
          revision: e1eb04597589f6dd41cecc75cfe81570e9ad655b
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-17-20250820-e1eb045-prd
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-17
  snapshot: acs-operator-index-ocp-v4-17-2025-08-20-e1eb045-prod
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: msugakov
    pac.test.appstudio.openshift.io/sha-title: Add 4.7.6 version (#174)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/e1eb04597589f6dd41cecc75cfe81570e9ad655b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-18-g6rhq
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-18
    appstudio.openshift.io/component: operator-index-ocp-v4-18
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: e1eb04597589f6dd41cecc75cfe81570e9ad655b
  name: acs-operator-index-ocp-v4-18-2025-08-20-e1eb045-prod
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-18
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:beb1f78a91a71c312a018493b61c5276c0f18e3927c4cc9bca70870099ac029b
      name: operator-index-ocp-v4-18
      source:
        git:
          revision: e1eb04597589f6dd41cecc75cfe81570e9ad655b
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-18-20250820-e1eb045-prd
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-18
  snapshot: acs-operator-index-ocp-v4-18-2025-08-20-e1eb045-prod
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: msugakov
    pac.test.appstudio.openshift.io/sha-title: Add 4.7.6 version (#174)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/e1eb04597589f6dd41cecc75cfe81570e9ad655b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-19-bj27r
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-19
    appstudio.openshift.io/component: operator-index-ocp-v4-19
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: e1eb04597589f6dd41cecc75cfe81570e9ad655b
  name: acs-operator-index-ocp-v4-19-2025-08-20-e1eb045-prod
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-19
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:cd536375d7954aa555f5b2186f6995966f4ea925ba79738d9ed6422b52250660
      name: operator-index-ocp-v4-19
      source:
        git:
          revision: e1eb04597589f6dd41cecc75cfe81570e9ad655b
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-19-20250820-e1eb045-prd
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-19
  snapshot: acs-operator-index-ocp-v4-19-2025-08-20-e1eb045-prod
