apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: check-catalog-template-has-only-released-images
  namespace: rh-acs-tenant
spec:
  description: This task is to prevent operator bundle images from quay.io or any repositories other than release ones to be added to the `master` branch. This is to make sure `master` is in good state to be released and would not require first cleaning unreleased bundles from it.
  params:
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the artifact with
      the application source code.
    type: string
  volumes:
  - name: workdir
    emptyDir: { }
  stepTemplate:
    volumeMounts:
    - mountPath: /var/workdir
      name: workdir
  steps:
  - name: use-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
    args:
    - use
    - $(params.SOURCE_ARTIFACT)=/var/workdir/source
  - name: check-bundle-images-in-catalog-template
    image: quay.io/konflux-ci/release-service-utils:latest@sha256:724d862b6c85a2dcae80e9d11e869c3dffbe4bc9def84d9c21deb66a0975c0b7
    workingDir: /var/workdir/source
    script: |
      #!/usr/bin/env bash
      set -euo pipefail

      if yq eval '.. | select(has("image")) | .image' catalog-template.yaml | grep -vE '^registry\.redhat\.io/advanced-cluster-security/rhacs-operator-bundle(:|@)'; then
        echo >&2 "catalog-template.yaml has image(s) not from registry.redhat.io/advanced-cluster-security/rhacs-operator-bundle. It is not allowed to merge such bundle images to master branch because it will no longer be releasable."
        exit 1
      fi
