apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/operator-index?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    # The on-push filter includes konflux/* branches which are created by Mintmaker so that CI runs for commits pushed
    # onto these branches even without PRs and so that Mintmaker/Renovate can automerge its updates without PRs.
    pipelinesascode.tekton.dev/on-cel-expression: |
      (event == "push" && target_branch.matches("^(master|konflux/references/master|konflux/mintmaker/.*)$")) ||
      (event == "pull_request" && body.action != "ready_for_review")
  labels:
    # The version should correspond to the serviceAccountName below. See the comment there.
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-19
  name: ready-for-master-merge
  namespace: rh-acs-tenant

spec:

  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'

  taskRunTemplate:
    # This pipeline doesn't have its own Component, but it has to have some ServiceAccount.
    # The pipeline has no special needs for SA, therefore, we re-use SA from one of the existing Components.
    serviceAccountName: build-pipeline-operator-index-ocp-v4-19

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  pipelineSpec:
    description: |
      This pipeline verifies whether a branch (or PR) can be merged to the `master` branch.
      `master` should always be releasable.

    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - description: Revision of the Source Repository
      name: revision
      type: string
    - default: quay.io/rhacs-eng/stackrox-operator-index
      description: Intermediate Image Repository
      name: oci-repo
      type: string
    - default: "1d"
      description: This sets the expiration time for intermediate OCI artifacts produced and used during builds after
        which they can be garbage collected.
      name: oci-artifact-expires-after
      type: string

    workspaces:
    - name: git-auth

    tasks:

    - name: clone-repository
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      - name: ociStorage
        value: $(params.oci-repo):konflux-ready-for-master-merge-$(params.revision).git
      - name: ociArtifactExpiresAfter
        value: $(params.oci-artifact-expires-after)
      taskRef:
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:efcce59f226b1426f7685917e41a50b73478f38fe9ac56c98f1e961effd4b6f0
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: basic-auth
        workspace: git-auth

    - name: check-catalog-template-has-only-released-images
      taskSpec:
        description: This task is to prevent operator bundle images from quay.io or any repositories other than release ones to be added to the `master` branch. This is to make sure `master` is in good state to be released and would not require first cleaning unreleased bundles from it.
        volumes:
        - name: workdir
          emptyDir: { }
        stepTemplate:
          volumeMounts:
          - mountPath: /var/workdir
            name: workdir
        steps:
        - name: use-trusted-artifact
          image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
          args:
          - use
          - $(tasks.clone-repository.results.SOURCE_ARTIFACT)=/var/workdir/source
        - name: check-bundle-images-in-catalog-template
          image: quay.io/konflux-ci/release-service-utils:latest@sha256:83d333e2d0dde26729256f5074817e885c7785c556e82ded88be9ecafd8518bc
          workingDir: /var/workdir/source
          script: |
            #!/usr/bin/env bash
            set -euo pipefail
            repo="registry.redhat.io/advanced-cluster-security/rhacs-operator-bundle"

            if yq eval '.. | select(has("image")) | .image' catalog-template.yaml | grep -vE '^registry\.redhat\.io/advanced-cluster-security/rhacs-operator-bundle(:|@)'; then
              echo >&2 "catalog-template.yaml has image(s) not from ${repo}. It is not allowed to merge such bundle images to master branch because it will no longer be releasable."
              exit 1
            fi
            echo "All good, no bundle images outside of ${repo} detected."
