package main

import (
	// needed for digest algorithm validation
	_ "crypto/sha256"

	"encoding/base64"
	"fmt"
	"log"
	"os"
	"slices"

	semver "github.com/Masterminds/semver/v3"
	"github.com/distribution/reference"
	"github.com/goccy/go-yaml"
)

const (
	inputFile                       = "bundles.yaml"
	outputFile                      = "catalog-template.yaml"
	iconFile                        = "icon.png"
	channelDeprecationMessage       = "This version is no longer supported. Switch to the `stable` channel or a channel for a more recent version that is still supported. Find supported versions in the RHACS support policy document: https://access.redhat.com/support/policy/updates/rhacs"
	bundleDeprecationMessage        = "This Operator version is no longer supported. Use a more recent version that is supported. Find supported versions in the RHACS support policy document: https://access.redhat.com/support/policy/updates/rhacs"
	versionBrokenMessage            = "This product version has known significant defects and should not be used. Use a more recent version that is supported. Find supported versions in the RHACS support policy document: https://access.redhat.com/support/policy/updates/rhacs"
	latestChannelDeprecationMessage = "The `latest` channel is no longer supported. Use the `stable` channel."
	latestChannelName               = "latest"
	stableChannelName               = "stable"
	first3MajorVersion              = "3.62.0"
	first4MajorVersion              = "4.0.0"
	brokenVersionSkippingOffset     = 2 // The number of versions to skip in the `skips` field of the channel entry for broken versions.
)

var headComment = []string{
	"--------------------------------------------------------------------------------",
	" DO NOT EDIT. This file is generated by cmd/generate-catalog/generate.go script.",
	" Any manual changes will be overwritten.",
	"--------------------------------------------------------------------------------",
}

func main() {
	err := generateCatalogTemplateFile()
	if err != nil {
		log.Fatalf("Failed to generate catalog template: %v", err)
	}
}

// generateCatalogTemplateFile reads the bundles.yaml file, processes the data, and writes the catalog template to the output file.
func generateCatalogTemplateFile() error {
	config, err := readInputFile(inputFile)
	if err != nil {
		return fmt.Errorf("failed to read bundle list file: %v", err)
	}

	pkg, err := generatePackageWithIcon()
	if err != nil {
		return fmt.Errorf("failed to generate package object with icon: %v", err)
	}
	channels := generateChannels(config.Versions)
	entries := generateChannelEntries(config.Versions, config.BrokenVersions)
	channels, err = populateChannelEntries(channels, entries)
	if err != nil {
		return fmt.Errorf("failed to add channel entries: %v", err)
	}

	deprecations := generateDeprecations(config.Versions, channels, config.OldestSupportedVersion, config.BrokenVersions)
	bundles := generateBundles(config.Images)

	ct := newCatalogTemplate()
	ct.addPackage(pkg)
	ct.addChannels(channels)
	ct.addDeprecations(deprecations)
	ct.addBundles(bundles)

	err = writeToFile(outputFile, ct)
	if err != nil {
		return fmt.Errorf("failed to write catalog template to file: %v", err)
	}

	fmt.Printf("%s generated successfully.\n", outputFile)

	return nil
}

// readInputFile unmarshals YAML file onto Configuration structure.
func readInputFile(filename string) (Configuration, error) {
	inputBytes, err := os.ReadFile(filename)
	if err != nil {
		return Configuration{}, fmt.Errorf("failed to read %s: %v", filename, err)
	}
	var input Input
	if err := yaml.Unmarshal(inputBytes, &input); err != nil {
		return Configuration{}, fmt.Errorf("failed to unmarshal YAML: %v", err)
	}

	oldest, err := semver.StrictNewVersion(input.OldestSupportedVersion)
	if err != nil {
		return Configuration{}, fmt.Errorf("invalid oldest_supported_version %q: %v", input.OldestSupportedVersion, err)
	}

	brokens := make(map[*semver.Version]bool, len(input.BrokenVersions))
	for _, s := range input.BrokenVersions {
		v, err := semver.StrictNewVersion(s)
		if err != nil {
			return Configuration{}, fmt.Errorf("invalid item in broken_versions %q: %v", s, err)
		}
		brokens[v] = true
	}

	var images []BundleImage
	for _, img := range input.Images {
		v, err := semver.StrictNewVersion(img.Version)
		if err != nil {
			return Configuration{}, fmt.Errorf("invalid version %q for image %q: %v", img.Version, img.Image, err)
		}
		images = append(images, BundleImage{
			Image:   img.Image,
			Version: v,
		})
	}

	// TODO: ROX-30604 check that image reference is associated with the provided version.
	if err := validateImageReferences(images); err != nil {
		return Configuration{}, err
	}

	versions := getAllVersions(images)
	if err := validateVersionsAreSorted(versions); err != nil {
		return Configuration{}, err
	}
	if err := hasGapInVersions(versions); err != nil {
		return Configuration{}, fmt.Errorf("version gap detected: %v", err)
	}
	if err := validateBrokenVersions(brokens, versions); err != nil {
		return Configuration{}, fmt.Errorf("invalid broken versions: %v", err)
	}
	if !slices.ContainsFunc(versions, oldest.Equal) {
		return Configuration{}, fmt.Errorf("oldest supported version %s is not present in the list of versions", oldest.Original())
	}

	return Configuration{
		OldestSupportedVersion: oldest,
		BrokenVersions:         brokens,
		Images:                 images,
		Versions:               versions,
	}, nil
}

// generatePackageWithIcon creates a new "olm.package" object with an operator icon.
func generatePackageWithIcon() (Package, error) {
	data, err := os.ReadFile(iconFile)
	if err != nil {
		return Package{}, fmt.Errorf("failed to read %s: %v", iconFile, err)
	}
	iconBase64 := base64.StdEncoding.EncodeToString(data)

	packageWithIcon := Package{
		Schema:         "olm.package",
		Name:           "rhacs-operator",
		DefaultChannel: stableChannelName,
		Icon: Icon{
			Base64data: iconBase64,
			MediaType:  "image/png",
		},
	}

	return packageWithIcon, nil
}

func generateChannels(versions []*semver.Version) []Channel {
	channels := make([]Channel, 0)

	for _, v := range versions {
		// latest channel is historically placed between rhacs-3.y and rhacs-4.y channels.
		if v.Original() == first4MajorVersion {
			latestChannel := newLatestChannel()
			channels = append(channels, latestChannel)
		}
		yStream := makeYStreamVersion(v)
		if len(channels) == 0 || !channels[len(channels)-1].YStreamVersion.Equal(yStream) {
			// Create a new channel for each new Y-Stream
			channel := newChannel(yStream)
			channels = append(channels, channel)
		}
	}
	// Create a stable channel at the end
	stableChannel := newStableChannel()
	channels = append(channels, stableChannel)

	return channels
}

func generateChannelEntries(versions []*semver.Version, skippedVersions map[*semver.Version]bool) []ChannelEntry {
	channelEntries := make([]ChannelEntry, 0)
	// very first version in the catalog replaces 3.61.0 and skipRanges starts from 3.61.0
	previousEntryVersion := semver.New(3, 61, 0, "", "")
	var previousYStreamVersion *semver.Version

	for _, v := range versions {
		if v.Minor() != previousEntryVersion.Minor() {
			previousYStreamVersion = makeYStreamVersion(previousEntryVersion)
		}

		catalogChannelEntry := newChannelEntry(v, previousEntryVersion, previousYStreamVersion, skippedVersions)
		channelEntries = append(channelEntries, catalogChannelEntry)

		previousEntryVersion = v
	}

	return channelEntries
}

func populateChannelEntries(channels []Channel, channelEntries []ChannelEntry) ([]Channel, error) {
	for i, channel := range channels {
		for _, entry := range channelEntries {
			if channelShouldHaveEntry(channel, entry) {
				channels[i].Entries = append(channels[i].Entries, entry)
			}
		}
	}
	return channels, nil
}

func channelShouldHaveEntry(channel Channel, entry ChannelEntry) bool {
	validForLatest := channel.Name == latestChannelName && entry.Version.Major() < 4
	validForStable := channel.Name == stableChannelName && entry.Version.Major() >= 4
	validForChannel := channel.YStreamVersion != nil &&
		entry.Version.Major() == channel.YStreamVersion.Major() &&
		entry.Version.Minor() <= channel.YStreamVersion.Minor()
	return validForLatest || validForStable || validForChannel
}

// generateDeprecations creates an object with a list of deprecations based on the provided versions.
func generateDeprecations(versions []*semver.Version, channels []Channel, oldestSupportedVersion *semver.Version, brokenVersions map[*semver.Version]bool) Deprecations {
	var deprecations []DeprecationEntry

	latestChannelDeprecationEntry := newChannelDeprecationEntry(latestChannelName, latestChannelDeprecationMessage)
	deprecations = append(deprecations, latestChannelDeprecationEntry)

	for _, channel := range channels {
		if channel.YStreamVersion != nil && channel.YStreamVersion.LessThan(oldestSupportedVersion) {
			channelDeprecation := newChannelDeprecationEntry(channel.Name, channelDeprecationMessage)
			deprecations = append(deprecations, channelDeprecation)
		}
	}

	// deprecate all bundles that are older than the oldest supported version
	for _, v := range versions {
		msg := ""
		if v.LessThan(oldestSupportedVersion) {
			msg = bundleDeprecationMessage
		}
		if brokenVersions[v] {
			msg = versionBrokenMessage
		}
		if msg != "" {
			deprecations = append(deprecations, newBundleDeprecationEntry(v, msg))
		}
	}

	return newDeprecations(deprecations)
}

// generateBundles creates a list of bundle entries based on the provided versions and their corresponding images.
func generateBundles(images []BundleImage) []BundleEntry {
	var bundleEntries []BundleEntry
	for _, img := range images {
		bundleEntries = append(bundleEntries, newBundleEntry(img.Image))
	}
	return bundleEntries
}

// writeToFile writes the resulting catalog template to the output YAML file.
func writeToFile(filename string, ct CatalogTemplate) error {
	headComment := yaml.HeadComment(headComment...)
	comments := yaml.CommentMap{
		"$": []*yaml.Comment{headComment}, // "$" means top-level comment
	}

	out, err := yaml.MarshalWithOptions(ct, yaml.WithComment(comments))
	if err != nil {
		return fmt.Errorf("failed to marshal catalog: %v", err)
	}
	if err := os.WriteFile(filename, out, 0644); err != nil {
		return fmt.Errorf("failed to write output: %v", err)
	}

	return nil
}

// validateVersionsAreSorted checks that the operator versions are sorted in ascending order and that there are no duplicates.
func validateVersionsAreSorted(versions []*semver.Version) error {
	for i := 0; i < len(versions)-1; i++ {
		currentVersion := versions[i]
		nextVersion := versions[i+1]
		if currentVersion.GreaterThanEqual(nextVersion) {
			return fmt.Errorf("versions are not sorted in ascending order: %s is not less than %s", currentVersion.Original(), nextVersion.Original())
		}
	}
	return nil
}

func hasGapInVersions(versions []*semver.Version) error {
	for i := 0; i < len(versions)-1; i++ {
		currentVersion := versions[i]
		nextVersion := versions[i+1]

		if currentVersion.Major() != nextVersion.Major() {
			if currentVersion.Major()+1 != nextVersion.Major() || nextVersion.Minor() != 0 || nextVersion.Patch() != 0 {
				return fmt.Errorf("invalid version %s: a new major version should start from %d.0.0", nextVersion.Original(), currentVersion.Major()+1)
			}
		}

		if currentVersion.Major() == nextVersion.Major() && currentVersion.Minor() != nextVersion.Minor() {
			if currentVersion.Minor()+1 != nextVersion.Minor() || nextVersion.Patch() != 0 {
				return fmt.Errorf("invalid version %s: a new minor version should be %s", currentVersion.Original(), nextVersion.Original())
			}
		}

		if currentVersion.Major() == nextVersion.Major() && currentVersion.Minor() == nextVersion.Minor() {
			if nextVersion.Patch() != currentVersion.Patch()+1 {
				return fmt.Errorf("invalid version %s: is not followed by %s", currentVersion.Original(), nextVersion.Original())
			}
		}
	}

	return nil
}

func validateBrokenVersions(brokenVersions map[*semver.Version]bool, versions []*semver.Version) error {
	for brokenVersion, _ := range brokenVersions {
		if !slices.ContainsFunc(versions, brokenVersion.Equal) {
			return fmt.Errorf("broken version %s is not present in the list of versions", brokenVersion.Original())
		}
	}
	return nil
}

// validateImageReferences checks that all images in the input bundle have valid container image references with a digest.
func validateImageReferences(images []BundleImage) error {
	for _, img := range images {
		if err := validateImageReference(img.Image); err != nil {
			return fmt.Errorf("invalid image reference %q: %w", img.Image, err)
		}
	}
	return nil
}

// validateImageReference validates that the provided image string is a valid container image reference with a digest
func validateImageReference(image string) error {
	// validate the image reference using the distribution/reference package
	ref, err := reference.Parse(image)
	if err != nil {
		return fmt.Errorf("cannot parse string as docker image %s: %w", image, err)
	}
	if _, ok := ref.(reference.Canonical); !ok {
		return fmt.Errorf("image reference does not include a digest")
	}
	return nil
}
