package main

import (
	// needed for digest algorithm validation
	_ "crypto/sha256"

	"encoding/base64"
	"fmt"
	"log"
	"maps"
	"os"
	"slices"

	semver "github.com/Masterminds/semver/v3"
	"github.com/distribution/reference"
	"github.com/goccy/go-yaml"
)

const (
	inputFile                       = "bundles.yaml"
	outputFile                      = "catalog-template.yaml"
	iconFile                        = "icon.png"
	channelDeprecationMessage       = "This version is no longer supported. Please switch to the `stable` channel or a channel for a more recent version that is still supported. Find supported versions in the RHACS support policy document: https://access.redhat.com/support/policy/updates/rhacs"
	bundleDeprecationMessage        = "This Operator version is no longer supported. Use a more recent version that is supported. Find supported versions in the RHACS support policy document: https://access.redhat.com/support/policy/updates/rhacs"
	versionBrokenMessage            = "This product version has known significant defects and should not be used. Use a more recent version that is supported. Find supported versions in the RHACS support policy document: https://access.redhat.com/support/policy/updates/rhacs"
	latestChannelDeprecationMessage = "The `latest` channel is no longer supported. Use the `stable` channel."
	first3MajorVersion              = "3.62.0"
	first4MajorVersion              = "4.0.0"
	resultYamlHeadComment           = `--------------------------------------------------------------------------------
# DO NOT EDIT. This file is generated by cmd/generate-catalog/generate.go script.
# Any manual changes will be overwritten.
#--------------------------------------------------------------------------------`
)

func main() {
	err := generateCatalogTemplateFile()
	if err != nil {
		log.Fatalf("Failed to generate catalog template: %v", err)
	}
}

// generateCatalogTemplateFile reads the bundles.yaml file, processes the data, and writes the catalog template to the output file.
func generateCatalogTemplateFile() error {
	config, err := readInputFile(inputFile)
	if err != nil {
		return fmt.Errorf("failed to read bundle list file: %v", err)
	}
	versions := getAllVersions(config.Images)
	skippedVersions := slices.Collect(maps.Keys(config.BrokenVersions))

	pkg, err := generatePackageWithIcon()
	if err != nil {
		return fmt.Errorf("failed to generate package object with icon: %v", err)
	}
	channels := generateChannels(versions, skippedVersions)
	deprecations := generateDeprecations(versions, config.OldestSupportedVersion, config.BrokenVersions)
	bundles := generateBundles(config.Images)

	ct := newCatalogTemplate()
	ct.addPackage(pkg)
	ct.addChannels(channels)
	ct.addDeprecations(deprecations)
	ct.addBundles(bundles)

	err = writeToFile(outputFile, ct)
	if err != nil {
		return fmt.Errorf("failed to write catalog template to file: %v", err)
	}

	fmt.Printf("%s generated successfully.\n", outputFile)

	return nil
}

// readInputFile unmarshals YAML file onto Configuration structure.
func readInputFile(filename string) (Configuration, error) {
	inputBytes, err := os.ReadFile(filename)
	if err != nil {
		return Configuration{}, fmt.Errorf("failed to read %s: %v", filename, err)
	}
	var input Input
	if err := yaml.Unmarshal(inputBytes, &input); err != nil {
		return Configuration{}, fmt.Errorf("failed to unmarshal YAML: %v", err)
	}

	var config Configuration
	oldest, err := semver.NewVersion(input.OldestSupportedVersion)
	if err != nil {
		return Configuration{}, fmt.Errorf("invalid oldest_supported_version %q: %v", input.OldestSupportedVersion, err)
	}

	brokens := make(map[*semver.Version]bool)
	for _, s := range input.BrokenVersions {
		v, err := semver.NewVersion(s)
		if err != nil {
			return Configuration{}, fmt.Errorf("invalid broken_versions %q: %v", s, err)
		}
		brokens[v] = true
	}

	var images []BundleImage
	for _, img := range input.Images {
		v, err := semver.NewVersion(img.Version)
		if err != nil {
			return Configuration{}, fmt.Errorf("invalid version %q for image %q: %v", img.Version, img.Image, err)
		}
		images = append(images, BundleImage{
			Image:   img.Image,
			Version: v,
		})
	}
	config = Configuration{
		OldestSupportedVersion: oldest,
		BrokenVersions:         brokens,
		Images:                 images,
	}

	if err := validateImages(config.Images); err != nil {
		return Configuration{}, err
	}
	if err := validateVersions(config.Images); err != nil {
		return Configuration{}, err
	}

	return config, nil
}

// getAllVersions extracts all operator versions from the input images.
func getAllVersions(images []BundleImage) []*semver.Version {
	versions := make([]*semver.Version, 0, len(images))
	for _, img := range images {
		versions = append(versions, img.Version)
	}
	return versions
}

// generatePackageWithIcon creates a new "olm.package" object with an operator icon.
func generatePackageWithIcon() (Package, error) {
	data, err := os.ReadFile(iconFile)
	if err != nil {
		return Package{}, fmt.Errorf("failed to read %s: %v", iconFile, err)
	}
	iconBase64 := base64.StdEncoding.EncodeToString(data)

	packageWithIcon := Package{
		Schema:         "olm.package",
		Name:           "rhacs-operator",
		DefaultChannel: "stable",
		Icon: Icon{
			Base64data: iconBase64,
			MediaType:  "image/png",
		},
	}

	return packageWithIcon, nil
}

// generateChannels creates a list of channels based on the provided bundle versions.
func generateChannels(versions []*semver.Version, skippedVersions []*semver.Version) []Channel {
	allChannels := make([]Channel, 0)
	// the list of ChannelEntry for specific major version (4.2 channel contains all <= 4.2.X versions starting from 4.0.0)
	majorEntries := make([]ChannelEntry, 0)
	// very first version in the catalog replaces 3.61.0 and skipRanges starts from 3.61.0
	previousEntryVersion := semver.MustParse("3.61.0")
	previousChannelVersion := semver.MustParse("3.61.0")
	var channel *Channel

	for _, v := range versions {
		// refresh major channel entries list when new major version is reached
		if v.Major() != previousEntryVersion.Major() {
			majorEntries = make([]ChannelEntry, 0)
		}

		// create a new channel entry for each new minor version (patch = 0)
		if v.Patch() == 0 {
			previousChannelVersion = previousEntryVersion
			if channel != nil {
				allChannels = append(allChannels, *channel)
				// Add "latest" channel when all "3.X.X" version are processed
				if v.Original() == first4MajorVersion {
					latestChannel := newLatestChannel(channel.Entries)
					allChannels = append(allChannels, latestChannel)
				}
			}
			channel = newChannel(v, slices.Clone(majorEntries))
		}

		catalogChannelEntry := newChannelEntry(v, previousEntryVersion, previousChannelVersion, skippedVersions)
		channel.Entries = append(channel.Entries, catalogChannelEntry)
		majorEntries = append(majorEntries, catalogChannelEntry)

		previousEntryVersion = v
	}

	// add the last channel entry for the last version processed
	allChannels = append(allChannels, *channel)
	// add "stable" channel when the last version is reached
	stableChannel := newStableChannel(channel.Entries)
	allChannels = append(allChannels, stableChannel)

	return allChannels
}

// generateDeprecations creates an object with a list of deprecations based on the provided versions.
func generateDeprecations(versions []*semver.Version, oldestSupportedVersion *semver.Version, brokenVersions map[*semver.Version]bool) Deprecations {
	var deprecations []DeprecationEntry
	var channelVersions []*semver.Version
	for _, v := range versions {
		// each 0 Patch version indicates a new channel.
		if v.Patch() == 0 {
			channelVersions = append(channelVersions, v)
		}
	}

	// deprecate all channels that are older than the oldest supported version
	for _, channelVersion := range channelVersions {
		if channelVersion.LessThan(oldestSupportedVersion) {
			channelname := generateChannelName(channelVersion)
			deprecations = append(deprecations, newChannelDeprecationEntry(channelname, channelDeprecationMessage))
		}
	}
	latestDeprecationEntry := newChannelDeprecationEntry("latest", latestChannelDeprecationMessage)
	deprecations = append(deprecations, latestDeprecationEntry)

	// deprecate all bundles that are older than the oldest supported version
	for _, v := range versions {
		if v.LessThan(oldestSupportedVersion) {
			deprecationMessage := bundleDeprecationMessage
			if brokenVersions[v] {
				deprecationMessage = versionBrokenMessage
			}
			deprecations = append(deprecations, newBundleDeprecationEntry(v, deprecationMessage))
		}
	}

	return newDeprecations(deprecations)
}

// generateBundles creates a list of bundle entries based on the provided versions and their corresponding images.
func generateBundles(images []BundleImage) []BundleEntry {
	var bundleEntries []BundleEntry
	for _, img := range images {
		bundleEntries = append(bundleEntries, newBundleEntry(img.Image))
	}
	return bundleEntries
}

// writeToFile writes the resulting catalog template to the output YAML file.
func writeToFile(filename string, ct CatalogTemplate) error {
	headComment := yaml.HeadComment(resultYamlHeadComment)
	comments := yaml.CommentMap{
		"$": []*yaml.Comment{headComment}, // "$" means top-level comment
	}

	out, err := yaml.MarshalWithOptions(ct, yaml.WithComment(comments))
	if err != nil {
		return fmt.Errorf("failed to marshal catalog: %v", err)
	}
	if err := os.WriteFile(filename, out, 0644); err != nil {
		return fmt.Errorf("failed to write output: %v", err)
	}

	return nil
}

// validateVersions checks that the operator versions are sorted in ascending order and that there are no duplicates.
func validateVersions(images []BundleImage) error {
	for i := 0; i < len(images)-1; i++ {
		version := images[i].Version
		nextVersion := images[i+1].Version
		if version == nil {
			return fmt.Errorf("version is not set for image %s", images[i].Image)
		}
		if nextVersion == nil {
			return fmt.Errorf("version is not set for image %s", images[i+1].Image)
		}
		if version.GreaterThanEqual(nextVersion) {
			return fmt.Errorf("operator versions are not sorted in ascending order: %s > %s", version.Original(), nextVersion.Original())
		}
	}
	return nil
}

// validateImages checks that all images in the input bundle have valid container image references with a digest.
func validateImages(images []BundleImage) error {
	for _, img := range images {
		if err := validateImageReference(img.Image); err != nil {
			return fmt.Errorf("invalid image reference %q: %w", img.Image, err)
		}
	}
	return nil
}

// validateImageReference validates that the provided image string is a valid container image reference with a digest
func validateImageReference(image string) error {
	// validate the image reference using the distribution/reference package
	ref, err := reference.Parse(image)
	if err != nil {
		return fmt.Errorf("cannot parse string as docker image %s: %w", image, err)
	}
	if _, ok := ref.(reference.Canonical); !ok {
		return fmt.Errorf("image reference does not include a digest")
	}
	return nil
}
